# 1. NumPy N-dimensional Array

The main data structure in NumPy is the ndarray,
which is a shorthand name for N-dimensional array. When working with NumPy, data in an
ndarray is simply referred to as an array. It is a fixed-sized array in memory that contains data
of the same type, such as integers or floating point values.

In [2]:
# create array
from numpy import array
# create array
l = [1.0, 2.0, 3.0]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


Running the example prints the contents of the ndarray, the shape, which is a one-
dimensional array with 3 elements, and the data type, which is a 64-bit floating point.

# 2. Functions to Create Arrays
There are more convenience functions for creating fixed-sized arrays that you may encounter or
be required to use. Let’s look at just a few.

## 2.1 Empty

The empty() function will create a new array of the specified shape. The argument to the
function is an array or tuple that specifies the length of each dimension of the array to create.
The values or content of the created array will be random and will need to be assigned before
use.

In [3]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)

[[ 1.27189941e-30 -2.54379882e-30  6.35949704e-31]
 [-2.54379882e-30  5.53276243e-30 -1.71706420e-30]
 [ 6.35949704e-31 -1.71706420e-30  9.85722042e-31]]


## 2.2 Zeroes
The zeros() function will create a new array of the specified size with the contents filled with
zero values. The argument to the function is an array or tuple that specifies the length of each
dimension of the array to create.

In [4]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 2.3 Ones
The ones() function will create a new array of the specified size with the contents filled with
one values. The argument to the function is an array or tuple that specifies the length of each
dimension of the array to create.

In [5]:
# create one array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


# 3. Combining arrays
NumPy provides many functions to create new arrays from existing arrays. Let’s look at two of
the most popular functions you may need or encounter.

## 3.1 Vertical stack
Given two or more existing arrays, you can stack them vertically using the vstack() function.
For example, given two one-dimensional arrays, you can create a new two-dimensional array
with two rows by vertically stacking them.

In [6]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


## 3.2 Horizontal stack
Given two or more existing arrays, you can stack them horizontally using the hstack() function.
For example, given two one-dimensional arrays, you can create a new one-dimensional array or
one row with the columns of the first and second arrays concatenated.

In [1]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)
