# 1. From List to Arrays


## 1.1 One-Dimensional List to Array
You may load your data or generate your data and have access to it as a list. You can convert a
one-dimensional list of data to an array by calling the array() NumPy function.

In [1]:
# create one-dimensional array
from numpy import array
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


## 1.2 Two-Dimensional List of Lists to Array
It is more likely in machine learning that you will have two-dimensional data. That is a table of
data where each row represents a new observation and each column a new feature. Perhaps you
generated the data or loaded it using custom code and now you have a list of lists. Each list
represents a new observation. You can convert your list of lists to a NumPy array the same way
as above, by calling the array() function.

In [2]:
# create two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


# 2. Array Indexing
Once your data is represented using a NumPy array, you can access it using indexing.

## 2.1 One-Dimensional Indexing
Generally, indexing works just like you would expect from your experience with other program-
ming languages, like Java, C#, and C++. For example, you can access elements using the
bracket operator [] specifying the zero-offset index for the value to retrieve.

In [3]:
# index a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])

11
55


Specifying integers too large for the bound of the array will cause an error.

In [4]:
# index array out of bounds
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

One key difference is that you can use negative indexes to retrieve values offset from the end
of the array. For example, the index -1 refers to the last item in the array. The index -2 returns
the second last item all the way back to -5 for the first item in the current example.

In [5]:
# negative array indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


## 2.2 Two-Dimensional Indexing
Indexing two-dimensional data is similar to indexing one-dimensional data, except that a comma
is used to separate the index for each dimension.

In [6]:
# index two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,0])

11


If we are interested in all items in the first row, we could leave the second dimension index
empty, for example:

In [7]:
# index row of two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,])

[11 22]


# 3. Array Slicing
So far, so good; creating and indexing arrays looks familiar. Now we come to array slicing, and
this is one feature that causes problems for beginners to Python and NumPy arrays. Structures
like lists and NumPy arrays can be sliced. This means that a subsequence of the structure
can be indexed and retrieved. This is most useful in machine learning when specifying input
variables and output variables, or splitting training rows from testing rows. Slicing is specified
using the colon operator : with a from and to index before and after the column respectively.
The slice extends from the from index and ends one item before the to index.

## 3.1 One-Dimensional Slicing
You can access all data in an array dimension by specifying the slice ‘:’ with no indexes.

In [8]:
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


The first item of the array can be sliced by specifying a slice that starts at index 0 and ends
at index 1 (one item before the to index).

In [9]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


We can also use negative indexes in slices. For example, we can slice the last two items in
the list by starting the slice at -2 (the second last item) and not specifying a to index; that
takes the slice to the end of the dimension.

In [10]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


## 3.2 Two-Dimensional Slicing
Let’s look at the two examples of two-dimensional slicing you are most likely to use in machine
learning.

### Split Input and Output Features
It is common to split your loaded data into input variables (X) and the output variable (y). We
can do this by slicing all rows and all columns up to, but before the last column, then separately
indexing the last column. For the input features, we can select all rows and all columns except
the last one by specifying : for in the rows index, and :-1 in the columns index.

`X = [:, :-1]`

For the output column, we can select all rows again using : and index just the last column
by specifying the -1 index.

`y = [:, -1]`

Putting all of this together, we can separate a 3-column 2D dataset into input and output
data as follows:

In [11]:
# split input and output data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


### Split Train and Test Rows

It is common to split a loaded dataset into separate train and test sets. This is a splitting of
rows where some portion will be used to train the model and the remaining portion will be used
to estimate the skill of the trained model. This would involve slicing all columns by specifying :
in the second dimension index. The training dataset would be all rows from the beginning to
the split point.

`train = data[:split, :]`

The test dataset would be all rows starting from the split point to the end of the dimension.

`test = data[split:, :]`

Putting all of this together, we can split the dataset at the contrived split point of 2.

In [12]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


# 4. Array Reshaping
After slicing your data, you may need to reshape it. For example, some libraries, such as
scikit-learn, may require that a one-dimensional array of output variables (y) be shaped as a
two-dimensional array with one column and outcomes for each column. Some algorithms, like
the Long Short-Term Memory recurrent neural network in Keras, require input to be specified
as a three-dimensional array comprised of samples, timesteps, and features. It is important to
know how to reshape your NumPy arrays so that your data meets the expectation of specific
Python libraries. We will look at these two examples.

## 4.1 Data Shape
NumPy arrays have a shape attribute that returns a tuple of the length of each dimension of
the array. For example:

In [13]:
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


A tuple with two lengths is returned for a two-dimensional array.

In [14]:
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


You can use the size of your array dimensions in the shape dimension, such as specifying
parameters. The elements of the tuple can be accessed just like an array, with the 0th index for
the number of rows and the 1st index for the number of columns. For example:

In [15]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
        [33, 44],
[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


## 4.2 Reshape 1D to 2D Array

It is common to need to reshape a one-dimensional array into a two-dimensional array with
one column and multiple arrays. NumPy provides the reshape() function on the NumPy array
object that can be used to reshape the data. The reshape() function takes a single argument
that specifies the new shape of the array. In the case of reshaping a one-dimensional array into
a two-dimensional array with one column, the tuple would be the shape of the array as the first
dimension (data.shape[0]) and 1 for the second dimension.

`data = data.reshape((data.shape[0], 1))`

Putting this all together, we get the following worked example.

In [16]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


## 4.3 Reshape 2D to 3D Array
It is common to need to reshape two-dimensional data where each row represents a sequence
into a three-dimensional array for algorithms that expect multiple samples of one or more time
steps and one or more features. A good example is the LSTM recurrent neural network model
in the Keras deep learning library. The reshape function can be used directly, specifying the
new dimensionality. This is clear with an example where each sequence has multiple time steps
with one observation (feature) at each time step. We can use the sizes in the shape attribute on
the array to specify the number of samples (rows) and columns (time steps) and fix the number
of features at 1.

`data.reshape((data.shape[0], data.shape[1], 1))`

Putting this all together, we get the following worked example.

In [18]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)
