# 1. Vectors

## 1.1 What is a Vector
A vector is a tuple of one or more values called scalars.

> Vectors are built from components, which are ordinary numbers. You can think of a vector as a list of numbers, and vector algebra as operations performed on the numbers in the list.

Vectors are often represented using a lowercase character such as v; for example:

`v= (v1,v2,v3)`

Where v1, v2, v3 are scalar values, often real values.

It is common to represent the target variable as a vector with the lowercase ywhen describing
the training of a machine learning algorithm. It is common to introduce vectors using a geometric
analogy, where a vector represents a point or coordinate in an n-dimensional space, where n
is the number of dimensions, such as 2. The vector can also be thought of as a line from the
origin of the vector space with a direction and a magnitude.

These analogies are good as a starting point, but should not be held too tightly as we often
consider very high dimensional vectors in machine learning. I find the vector-as-coordinate the
most compelling analogy in machine learning. Now that we know what a vector is, let’s look at
how to define a vector in Python.

## 1.2 Defining a Vector
We can represent a vector in Python as a NumPy array. A NumPy array can be created from
a list of numbers. For example, below we define a vector with the length of 3 and the integer
values 1, 2 and 3.

In [1]:
# create a vector
from numpy import array
# define vector
v = array([1, 2, 3])
print(v)

[1 2 3]


## 1.3 Vector Arithmetic
In this section will demonstrate simple vector-vector arithmetic, where all operations are
performed element-wise between two vectors of equal length to result in a new vector with the
same length.

### 1.3.1 Vector addition
Two vectors of equal length can be added together to create a new third vector.

`c = a + b`

The new vector has the same length as the other two vectors. Each element of the new vector is calculated as the addition of the elements of the other vectors at the same index; for example:

`c = (a1 + b1,a2 + b2,a3 + b3)`

We can add vectors directly in Python by adding NumPy arrays.

In [2]:
# vector addition
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# add vectors
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


### 1.3.2 Vector Subtraction
One vector can be subtracted from another vector of equal length to create a new third vector.

`c = a − b`

As with addition, the new vector has the same length as the parent vectors and each element of the new vector is calculated as the subtraction of the elements at the same indices.

`c = (a1 − b1,a2 − b2,a3 − b3)`

The NumPy arrays can be directly subtracted in Python.

In [3]:
# vector subtraction
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([0.5, 0.5, 0.5])
print(b)
# subtract vectors
c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


### 1.3.3 Vector Multiplication
Two vectors of equal length can be multiplied together.

`c = a × b`

As with addition and subtraction, this operation is performed element-wise to result in a new vector of the same length.

`c = (a1 × b1,a2 × b2,a3 × b3)`

We can perform this operation directly in NumPy.

In [4]:
# vector multiplication
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


### 1.3.4 Vector Division
Two vectors of equal length can be divided.

`c = a / b`

As with other arithmetic operations, this operation is performed element-wise to result in a new vector of the same length.

`c = (a1 / b1, a2 / b2, a3 / b3)`

We can perform this operation directly in NumPy.

In [5]:
# vector division
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# divide vectors
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


## 1.4 Vector Dot Product
We can calculate the sum of the multiplied elements of two vectors of the same length to give a
scalar. This is called the dot product, named because of the dot operator used when describing
the operation.

> The dot product is the key tool for calculating vector projections, vector decompositions, and determining orthogonality. The name dot product comes from the symbol used to denote it.
>
> --- Page 110, *No Bullshit Guide To Linear Algebra*, 2017.

`c = a · b`

The operation can be used in machine learning to calculate the weighted sum of a vector.
The dot product is calculated as follows:

`c = (a1 × b1 + a2 × b2 + a3 × b3)`

We can calculate the dot product between two vectors in Python using the dot() function on a NumPy array.

In [6]:
# vector dot product
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


## 1.5 Vector-Scalar Multiplication
A vector can be multiplied by a scalar, in effect scaling the magnitude of the vector. To keep
notation simple, we will use lowercase s to represent the scalar value.

`c = s × v`

The multiplication is performed on each element of the vector to result in a new scaled vector of the same length.

`c = (s × v1,s × v2,s × v3)`

We can perform this operation directly with the NumPy array.

In [7]:
# vector-scalar multiplication
from numpy import array
# define vector
a = array([1, 2, 3])
print(a)
# define scalar
s = 0.5
print(s)
# multiplication
c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]
