# 2. Vector Norms
Calculating the length or magnitude of vectors is often required either directly as a regularization method in machine learning, or as part of broader vector or matrix operations. In this tutorial, you will discover the different ways to calculate vector lengths or magnitudes, called the vector norm. After completing this tutorial, you will know:

- The L<sup>1</sup> norm that is calculated as the sum of the absolute values of the vector.
- The L<sup>2</sup> norm that is calculated as the square root of the sum of the squared vector values.
- The max norm that is calculated as the maximum vector values.

## 2.1 Vector Norm
Calculating the size or length of a vector is often required either directly or as part of a broader vector or vector-matrix operation. The length of the vector is referred to as the vector norm or the vector’s magnitude.

> The length of a vector is a nonnegative number that describes the extent of the vector in space, and is sometimes referred to as the vector’s magnitude or the norm.
>
> --- Page 112, *No Bullshit Guide To Linear Algebra*, 2017.

The length of the vector is always a positive number, except for a vector of all zero values.
It is calculated using some measure that summarizes the distance of the vector from the origin
of the vector space. For example, the origin of a vector space for a vector with 3 elements is
(0,0,0). Notations are used to represent the vector norm in broader calculations and the type
of vector norm calculation almost always has its own unique notation. We will take a look at a
few common vector norm calculations used in machine learning.

## 2.2 Vector *L*<sup>1</sup>
The length of a vector can be calculated using the *L*<sup>1</sup> norm, where the 1 is a superscript of the L. The notation for the *L*<sup>1</sup> norm of a vector is ||*v*||<sub>1</sub>, where 1 is a subscript. As such, this length is sometimes called the taxicab norm or the Manhattan norm.

*L*<sup>1</sup>(*v*) = ||*v*||<sub>1</sub>

The *L*<sup>1</sup> norm is calculated as the sum of the absolute vector values, where the absolute value
of a scalar uses the notation |*a*<sub>1</sub>|. In effect, the norm is a calculation of the Manhattan distance
from the origin of the vector space.

||*v*||<sub>1</sub> = |*a*<sub>1</sub>| + |*a*<sub>2</sub>| + |*a*<sub>3</sub>|

> In several machine learning applications, it is important to discriminate between elements that are exactly zero and elements that are small but nonzero. In these cases, we turn to a function that grows at the same rate in all locations, but retains mathematical simplicity: the *L*<sup>1</sup> norm.
>
> --- Pages 39-40, *Deep Learning*, 2016.

The *L*<sup>1</sup> norm of a vector can be calculated in NumPy using the norm() function with a
parameter to specify the norm order, in this case 1.

In [2]:
# vector L1 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


The *L*<sup>1</sup> norm is often used when fitting machine learning algorithms as a regularization
method, e.g. a method to keep the coefficients of the model small, and in turn, the model less
complex.

## 2.3 Vector *L*<sup>2</sup>
The length of a vector can be calculated using the *L*<sup>2</sup> norm, where the 2 is a superscript of the
*L*. The notation for the $L^2$ norm of a vector is ||*v*||<sub>2</sub> where 2 is a subscript.

*L*<sup>2</sup>(*v*) = ||*v*||<sub>2</sub>

The *L*<sup>2</sup> norm calculates the distance of the vector coordinate from the origin of the vector
space. As such, it is also known as the Euclidean norm as it is calculated as the Euclidean
distance from the origin. The result is a positive distance value. The *L*<sup>2</sup> norm is calculated as
the square root of the sum of the squared vector values.

$||v||_2 = \sqrt{a_1^2 + a_2^2 + a_3^3}$

The $L^2$ norm of a vector can be calculated in NumPy using the `norm()` function with default
parameters.

In [3]:
# vector L2 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


Like the $L^1$ norm, the $L^2$ norm is often used when fitting machine learning algorithms as a
regularization method, e.g. a method to keep the coefficients of the model small and, in turn,
the model less complex. By far, the $L^2$ norm is more commonly used than other vector norms
in machine learning.

## 2.4 Vector Max Norm
The length of a vector can be calculated using the maximum norm, also called max norm. Max norm of a vector is referred to as $L^{inf}$ where inf is a superscript and can be represented with the infinity symbol. The notation for max norm is $||v||_{inf}$, where inf is a subscript.

$L^{inf} (v) = ||v||_{inf}$

The max norm is calculated as returning the maximum value of the vector, hence the name.

$||v||_{inf} = max(a_1,a_2,a_3)$

The max norm of a vector can be calculated in NumPy using the `norm()` function with the order parameter set to `inf`.

In [4]:
# vector max norm
from math import inf
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0


Max norm is also used as a regularization in machine learning, such as on neural network
weights, called max norm regularization.