# 5. Matrix Operations
Matrix operations are used in the description of many machine learning algorithms. Some operations can be used directly to solve key equations, whereas others provide useful shorthand or foundation in the description and the use of more complex matrix operations. In this tutorial, you will discover important linear algebra matrix operations used in the description of machine learning methods. After completing this tutorial, you will know:
- The Transpose operation for flipping the dimensions of a matrix.
- The Inverse operations used in solving systems of linear equations.
- The Trace and Determinant operations used as shorthand notation in other matrix operations.

## 5.1 Transpose
A defined matrix can be transposed, which creates a new matrix with the number of columns and rows flipped. This is denoted by the superscript $T$ next to the matrix $A^T$.

$C = A^T$

An invisible diagonal line can be drawn through the matrix from top left to bottom right on which the matrix can be flipped to give the transpose.

$A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}$

$A^T = \begin{bmatrix} 1 & 3 & 5 \\ 2 & 4 & 6 \end{bmatrix}$

The operation has no effect if the matrix is symmetrical, e.g. has the same number of columns and rows and the same values at the same locations on both sides of the invisible diagonal line.

> The columns of $A^T$ are the rows of $A$.
>
> -- Page 109, *Introduction to Linear Algebra*, Fifth Edition, 2016.

We can transpose a matrix in NumPy by calling the T attribute.

In [1]:
# transpose matrix
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# calculate transpose
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


The transpose operation provides a short notation used as an element in many matrix
operations.

## 5.2 Inverse
Matrix inversion is a process that finds another matrix that when multiplied with the matrix, results in an identity matrix. Given a matrix $A$, find matrix $B$, such that $AB = I^n$ or $BA = I^n$.

The operation of inverting a matrix is indicated by a −1 superscript next to the matrix; for example, $A^−1$. The result of the operation is referred to as the inverse of the original matrix; for example, $B$ is the inverse of $A$.

$B = A^{−1}$

A matrix is invertible if there exists another matrix that results in the identity matrix, where not all matrices are invertible. A square matrix that is not invertible is referred to as singular.

> Whatever $A$ does, $A^{−1}$ undoes.
>
> -- Page 83, *Introduction to Linear Algebra*, Fifth Edition, 2016.

The matrix inversion operation is not computed directly, but rather the inverted matrix is discovered through a numerical operation, where a suite of efficient methods may be used, often involving forms of matrix decomposition.

> However, $A^1$ is primarily useful as a theoretical tool, and should not actually be used in practice for most software applications.
>
> -- Page 37, *Deep Learning*, 2016.

A matrix can be inverted in NumPy using the `inv()` function.

In [2]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
# multiply A and B
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


Note, your specific results may vary given differences in floating point precision on different hardware and software versions. Matrix inversion is used as an operation in solving systems of equations framed as matrix equations where we are interested in finding vectors of unknowns. A good example is in finding the vector of coefficient values in linear regression.